apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordpress.name" . }}
  template:
    metadata:
      labels:
        {{- include "wordpress.labels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb" # Adjust this if using an external database
            - name: WORDPRESS_DB_USER
              value: "wordpress"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: mariadb-password
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}

Unable to create application: application spec for wordpress is invalid: InvalidSpecError: Unable to generate manifests in wordpress: rpc error: code = Unknown desc = `helm template . --name-template wordpress --namespace wordpress --kube-version 1.29 --values <path to cached source>/wordpress/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: parse error at (wordpress/templates/ingress.yaml:13): bad character U+005B '[' Use --debug flag to render out invalid YAML